# Generated by Django 2.2.7 on 2019-11-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=40)),
                ('end', models.CharField(max_length=100)),
                ('titulacao', models.CharField(max_length=52)),
                ('fone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('nota_final', models.FloatField()),
                ('nome_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Aluno')),
                ('titulo_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('ano_letivo', models.DateField()),
                ('carga', models.IntegerField()),
                ('nome_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Professor')),
                ('titulo_disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Disciplina')),
            ],
        ),
    ]
