# Generated by Django 2.2.7 on 2019-11-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='titulo',
            new_name='titulo_dis',
        ),
    ]
