# Generated by Django 2.2.7 on 2019-11-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20191126_1314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alocacao',
            table='Alocação',
        ),
    ]
